### ISSUE TITLE
Optimizer auswählen

### ISSUE THREAD

**Issue by AnnaDobelmann** [baalIsBack/Datenanalyse-und-Daten-Mining#14]
Adam vs Adadelta vs SGD
Es gilt herauszufinden, welcher optimizer die besten Ergebnisse liefert.

**Comment by Julian-Christian** [comment]
Bei SGD ist mehr feintuning gefragt und bei Adam nicht.

**Comment by Julian-Christian** [comment]
SGD ist schneller und Adam ist automatisierter
