### ISSUE TITLE
Umsetzung: hidden_layer sind die inputs pro layer

### ISSUE THREAD

**Issue by Julian-Christian** [baalIsBack/Datenanalyse-und-Daten-Mining#4]
- hidden_layer sind die inputs pro layer

- abhängig von Aktivierungsfunktion -> relu braucht man layer angeben

- Bei anderen Aktivierungsfunktionen ggf. nicht

**Comment by AnnaDobelmann** [comment]
Irrelevant - War lediglich Kommentar für Annas Code
